server:
  port: 8081

spring:
  application:
    name: email-ai-analyzer
  
  datasource:
    url: jdbc:mysql://localhost:3306/email_db
    username: email_user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2
        options:
          num_gpu: 1
          main_gpu: 0
          temperature: 0.3

email:
  analysis:
    cron: "0 */5 * * * *"

logging:
  level:
    root: INFO
    com.logilink.emailanalyzer: DEBUG
