spring:
  application:
    name: email-ai-analyzer
  
  datasource:
    url: jdbc:postgresql://localhost:5432/email_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2
        options:
          num_gpu: 1
          main_gpu: 0
          temperature: 0.3

email:
  analysis:
    cron: "0 */5 * * * *"

logging:
  level:
    root: INFO
    com.logilink.emailanalyzer: DEBUG
